### ISSUE TITLE
New User Registration page - expected Password characters are 7 but on reset password page no. of characters for same field are 6

### ISSUE THREAD

**Issue by nikhilgkulkarni1** [gregoryagu/IssueTracker#12]
New User Registration page - expected Password characters are 7 but on reset password page no. of characters for same field are 6
![6char](https://user-images.githubusercontent.com/44431454/50401793-3fa99a00-07b7-11e9-925a-52d6a53d7ee5.png)
![7 char](https://user-images.githubusercontent.com/44431454/50401797-4801d500-07b7-11e9-8780-b6eba3bf0042.png)

**Comment by gregoryagu** [comment]
This has been fixed.
