### ISSUE TITLE
Trashed Project title appears on UI.

### ISSUE THREAD

**Issue by nikhilgkulkarni1** [gregoryagu/IssueTracker#15]
![fail3](https://user-images.githubusercontent.com/44431454/50404365-fc5a2600-07cc-11e9-87e2-5633f22adb0c.png)
![fail1](https://user-images.githubusercontent.com/44431454/50404366-fc5a2600-07cc-11e9-9ad1-1448a677c385.png)

**Comment by gregoryagu** [comment]
The UI should not allow the Root to be deleted.

**Comment by gregoryagu** [comment]
I tried, and the UI did not allow me to delete the root.  How did you do that?

**Comment by nikhilgkulkarni1** [comment]
I apologize for this issue - I have retested it and it's working perfect , there was some confusion from my side.
