### ISSUE TITLE
Site is again asking me for sign in even if i m not clearing cache/cookies and closed the tab.

### ISSUE THREAD

**Issue by pravin123456** [gregoryagu/IssueTracker#17]
URL: https://traken.net/

Steps:
1. Sign up with proper information.
2. Go to app page.
3. Close the tab
4. Open new tab and enter URL: https://traken.net/ again
5. It will ask you for sign up again

**Comment by gregoryagu** [comment]
https://traken.net is the landing page.  https://traken.app is the app.  If you go directly to traken.app, it will log you in directly.
Maybe a cookie is needed so the user is not shown the landing page if he is already signed up.

**Comment by nikhilgkulkarni1** [comment]
P1

**Comment by gregoryagu** [comment]
Closing this, as it is expected behavior.  The user can just click the Sign-in button.
