### ISSUE TITLE
No Sign In option visible on landing page, user need to scroll down to get "LOGIN" option visible

### ISSUE THREAD

**Issue by pravin123456** [gregoryagu/IssueTracker#18]
![image](https://user-images.githubusercontent.com/13730285/50405129-498ec580-07d6-11e9-9a6d-bbcee083e6f5.png)

**Comment by nikhilgkulkarni1** [comment]
P2

**Comment by gregoryagu** [comment]
I have changed the behavior so the NavBar is always at the top. Before, it was not visible when the page first opened.
