### ISSUE TITLE
Url in mail is not working

### ISSUE THREAD

**Issue by nikhilgkulkarni1** [gregoryagu/IssueTracker#3]
Following url - is not working which I got in an email.
### http://cfdj8l/EQh56bIpLmG/EYYFvltP3M5h1OGjmpmRC1JB99f3ktODxAmle4w9HyDyBVibfWky5ULf1l0Q+1AG2sSwqXnKk4qYz929/UIYT+4jNuTQ6v6Z7aCVYw6MoXv+j6WLBxTJMnaxnVZ7uorxHryiyM81wvLjtrw1YWI+INsHd5TGkkd4Vy6Cd/GO3sJ/scAwgvbPk8vzWXxz9IeEfN9bE9IQO59WQfJHH2C5H0+nQ7lwEfL7we4JiU+5nHeTZy4e5AA==

**Comment by gregoryagu** [comment]
I have confirmed that this is an issue and needs to be fixed

**Comment by gregoryagu** [comment]
This has been fixed. Please test again.
