### ISSUE TITLE
Entire application ---- History :: Latest activities should be on TOP  // user needs to scroll down for latest records.

### ISSUE THREAD

**Issue by nikhilgkulkarni1** [gregoryagu/IssueTracker#43]
![fail3](https://user-images.githubusercontent.com/44431454/50438001-20734f80-0912-11e9-8b96-f8cfa42cb842.png)

**Comment by gregoryagu** [comment]
There is a setting to control that, as some users like it from old to new, and some from new to old.  For example, GitHub has oldest on top.
