### ISSUE TITLE
Progress % can not be a negative value.

### ISSUE THREAD

**Issue by nikhilgkulkarni1** [gregoryagu/IssueTracker#46]
![image](https://user-images.githubusercontent.com/44431454/50441867-a8f9ec00-0922-11e9-930b-be2ebd9c65ed.png)

**Comment by gregoryagu** [comment]
This has been reproduced and fixed.

**Comment by nikhilgkulkarni1** [comment]
Issue is present in entire application where Progress column is present.


![image](https://user-images.githubusercontent.com/44431454/50477026-9352f800-09f0-11e9-8deb-671943fda260.png)
