### ISSUE TITLE
UI misalignment for progress  -  on edit and save.

### ISSUE THREAD

**Issue by nikhilgkulkarni1** [gregoryagu/IssueTracker#47]
#1 :: Create a sub-task and save it.
#2 :: Edit same sub-task and update Progress.
#3 :: Save changes.

![image](https://user-images.githubusercontent.com/44431454/50442455-05f6a180-0925-11e9-86f5-3d892f50515f.png)

**Comment by gregoryagu** [comment]
This is a known issue that I have been unable to resolve. Sometimes is ok, others not.
