### ISSUE TITLE
Alignment issues while writing comments for a task.

### ISSUE THREAD

**Issue by hereiamjeethik** [gregoryagu/IssueTracker#48]
Write some content on the text wizard in paragraph mode and change it to Quotation. the existing words indent is increased.
<img width="1792" alt="screenshot 2018-12-26 at 4 07 57 pm" src="https://user-images.githubusercontent.com/17821777/50443288-9bdffb80-0928-11e9-8512-87cae8fbe990.png">

**Comment by gregoryagu** [comment]
That is the style for a quotation.
