### ISSUE TITLE
Allowing Empty comments to be saved for a task

### ISSUE THREAD

**Issue by hereiamjeethik** [gregoryagu/IssueTracker#49]
Add no content into the comment section and save, it is allowing to save the comments.
<img width="929" alt="screenshot 2018-12-26 at 4 19 01 pm" src="https://user-images.githubusercontent.com/17821777/50443620-368d0a00-092a-11e9-9187-84f0d3d73c52.png">

**Comment by gregoryagu** [comment]
This was reproduced and fixed.
