### ISSUE TITLE
Create Task :: Page becomes unresponsive when submitted new task.

### ISSUE THREAD

**Issue by nikhilgkulkarni1** [gregoryagu/IssueTracker#5]
Expected :: UI should remain active.
Actual :: UI becomes unresponsive.

Steps :: 

#1 :: Login to application.
#2 :: Go to explorer tab. 
#3 :: Create a new project.
#4 :: Under project create new task and submit.
![fail](https://user-images.githubusercontent.com/44431454/50398114-1713a700-079b-11e9-878a-ef8b3545c7b8.png)

**Comment by gregoryagu** [comment]
I cannot reproduce.

Can you open developer Tools (F12) and go to the Console and see if there are any error messages?

**Comment by nikhilgkulkarni1** [comment]
Right now not able to reproduce - will keep eye on this issue - if gets reproduced will add details.
