### ISSUE TITLE
Not able to mark notifications as "Read"

### ISSUE THREAD

**Issue by nikhilgkulkarni1** [gregoryagu/IssueTracker#53]
Below mentioned point is mentioned in description of contest - but didnt found any option which performs this operation..
14. View notifications and mark them as read

![image](https://user-images.githubusercontent.com/44431454/50446096-1153c800-0939-11e9-89c0-786c193efa0d.png)

**Comment by gregoryagu** [comment]
There are two ways - Mark All as Read button, and also the "x" on the right hand side.  Maybe this needs to be more clear.

**Comment by gregoryagu** [comment]
I was unable to make this look any better, so I am closing at this time.
