### ISSUE TITLE
First Name / Last Name can not be a number // we should not allow this.

### ISSUE THREAD

**Issue by nikhilgkulkarni1** [gregoryagu/IssueTracker#54]
![image](https://user-images.githubusercontent.com/44431454/50446182-93dc8780-0939-11e9-9d20-29b25cbfcf7f.png)

**Comment by gregoryagu** [comment]
While unusual, I don't think it would be correct to validate the name to ensure it is not numbers. Although unusual, it is still a valid name as far as the system is concerned.  

So this is not really a bug.
