### ISSUE TITLE
P1 :: For New Team "Explorer tab" is blank.

### ISSUE THREAD

**Issue by nikhilgkulkarni1** [gregoryagu/IssueTracker#57]
Expected :: At least default node should get displayed to the new team.
Actual :: Explorer tab is blank for new team.

Actual :: 
![image](https://user-images.githubusercontent.com/44431454/50474434-e45dee80-09e6-11e9-84da-fa32a47a989f.png)

Expected ::
![image](https://user-images.githubusercontent.com/44431454/50474671-ec6a5e00-09e7-11e9-9ff8-055324de2432.png)

**Comment by nikhilgkulkarni1** [comment]
I agree - but new can not create any new item by clicking on + icon.

**Comment by gregoryagu** [comment]
Ok, will fix
