### ISSUE TITLE
Team Info :: Save / Cancel button should not get shown when clicked.

### ISSUE THREAD

**Issue by nikhilgkulkarni1** [gregoryagu/IssueTracker#58]
Expected :: On click of Save / Cancel button user may feel like modified data is not saved because we dont show alert message on save - also though user clicks on Save / Cancel -- still button remains on screen , what we can do is on click of save / cancel remove both buttons from UI. 

![image](https://user-images.githubusercontent.com/44431454/50476110-e9be3780-09ec-11e9-94b4-23910a770e8c.png)

**Comment by gregoryagu** [comment]
This has been reproduced and fixed by removing the buttons.  In the top left is the correct save button that will close the edit form.
