### ISSUE TITLE
P3 :: Suggestion :: Need platform where team members can be added / removed from one team to other.

### ISSUE THREAD

**Issue by nikhilgkulkarni1** [gregoryagu/IssueTracker#59]
I think team members are not constant , so we should allow team members to get shuffled from one team to other.
Also team member and team can be a one to many relation i.e. single team member can be part of multiple teams.

As per current implementation new member becomes part of selected team only and no option to shuffle him to other team.

**Comment by gregoryagu** [comment]
I agree with you, but this can already be done:
1. Create Team A and Invite Member Joe who is not yet in the system.  A new login is created.
2. Create Team B and also invite Member Joe.  He will be able to log into Team B, or Team A by switching directories.  So it is only one login, but he is now a member of two Teams.

However, I do agree with you that on the Team Page, one should be able to see all of the Teams that you are a member of, and then show all of the Team Members for those teams.  Then we could allow a team member to be added or removed from that page. In other words, he could be shuffled to other teams easily. This should only be available to the Team Owner.

**Comment by Grujko** [comment]
I also did not see option for deleting team member.
I added 2 team members with the same name, and there is no option for deleting on of them.

**Comment by gregoryagu** [comment]
There is now an option to cancel an invite.
