### ISSUE TITLE
SignUp: Space is accepted in password field while signing up

### ISSUE THREAD

**Issue by jj3408** [gregoryagu/IssueTracker#63]
While signing up, in password field - if you are entering spaces only still it's being considered as valid input.

Ideally Spaces are not allowed for inputs in password type fields.

Please check.

**Comment by jj3408** [comment]
![image](https://user-images.githubusercontent.com/42144023/50545884-ac071c00-0c43-11e9-8bb9-25fa5072e484.png)

This is what happening after submitting signup request with only spaces in password field. Please check attached screenshot.

**Comment by gregoryagu** [comment]
After some research, it appears that a space is a valid password character, and if a user wants to use it, it does not create any issues. 

I have never actually seen or heard of a person using a space, but it can be done.
