### ISSUE TITLE
SignUp: Email validation field is not working properly

### ISSUE THREAD

**Issue by jj3408** [gregoryagu/IssueTracker#64]
![image](https://user-images.githubusercontent.com/42144023/50545898-1029e000-0c44-11e9-957e-fd2a96b624dc.png)

Even though correct email is not entered, it's not showing error message. Please find screenshot attached.

**Comment by gregoryagu** [comment]
It's being validated by jquery, and their validation allows the user to enter without a .com/.net etc.
