### ISSUE TITLE
P1 - User is not able to see the content of added file into the Task

### ISSUE THREAD

**Issue by Grujko** [gregoryagu/IssueTracker#69]
Environment: Windows 10 pro
Browser: Google chrome

Reproduction steps:
1) Log in on the page.
2) Click on wanted Task from the "Dashboard- Qick View" table. data: Task Grujko.
1) Click on "Files" button.
3) Click on "Choose file(s)" button.
4) Select file from the drive.
5) From the "Upload box" click on "Upload" button.
6) After uploading, click "Close" button to close "Upload box".
7) Click on the uploaded file and check the contest.

Expected results:
User should be able to see valid content from the uploaded file.

Actual results: 
User is not able to see valid content from the uploaded file.

Attachment: video link file     https://screencast-o-matic.com/watch/cFlwqJr98r

Console message : Failed to load resource: the server responded with a status of 500 ()

**Comment by Grujko** [comment]
Can you please tell me is there an option for deleting already added file?

**Comment by gregoryagu** [comment]
There is not, but there should be

**Comment by nikhilgkulkarni1** [comment]
Page Crash -- P1
