### ISSUE TITLE
Search goes infinite 

### ISSUE THREAD

**Issue by Ahsan8036** [gregoryagu/IssueTracker#7]
I searched for Task A not showing anything. I had to refresh page
![search](https://user-images.githubusercontent.com/46100333/50398933-62c75000-079d-11e9-90ec-5dd2d4f9f604.PNG)

**Comment by Ahsan8036** [comment]
Yes there is an issue, when i search for task A and select match by word this happens again
![image](https://user-images.githubusercontent.com/46100333/50399746-7fff1d00-07a3-11e9-95fe-9770669ca03c.png)

**Comment by Ahsan8036** [comment]
when i search with id or tag it shows all
![image](https://user-images.githubusercontent.com/46100333/50399858-4e3a8600-07a4-11e9-9f27-61fb32687e74.png)

**Comment by gregoryagu** [comment]
ok

**Comment by gregoryagu** [comment]
This was reproduced and fixed.
