### ISSUE TITLE
Archived Task is not visible in the platform.

### ISSUE THREAD

**Issue by Grujko** [gregoryagu/IssueTracker#70]
Environment: Windows 10 pro
Browser: Google Chrome

Reproduction steps:
1) Log in on the page.
2) Click on wanted Task from the "Dashboard- Quick View" table. data: Task Grujko. 
3) Click on the "Desk" icon to archived closed task Grujko.
4) From the "Confirm" box, click on "Yes" button to confirm wanted action.
5) Search for the archived Task in the system.

Expected results:
User should be able to archive wanted task, and to see it at the platform database.

Actual results:
User received information that task is archived, but the archived task is not visible in the platform.

Notification: I also archived task with the name Grujko 11.
 I archived 2 tasks, but both of them are not visible in the system.

If this is not a bug, can you write me  where can I see archived tasks?

**Comment by gregoryagu** [comment]
Try this option in the search page:

![image](https://user-images.githubusercontent.com/3810620/50595550-d983dd80-0e6e-11e9-867c-7c2752b5567b.png)

**Comment by nikhilgkulkarni1** [comment]
Working as expected.

![image](https://user-images.githubusercontent.com/44431454/50635049-aa589380-0f76-11e9-8cc5-228bae027ac7.png)

**Comment by Grujko** [comment]
Thanks!
