### ISSUE TITLE
Edit Profile - Suggestion about e-mail verification

### ISSUE THREAD

**Issue by Grujko** [gregoryagu/IssueTracker#74]
I successful changed my First and Last name on my profile.
But I think that there should  be automatically send verification e-mail that data is changed.
Instead of manual by clicking on the "Send verification" link.
This is more secure issue.
![verification link](https://user-images.githubusercontent.com/46247028/50609868-49c34b00-0ed1-11e9-85f3-6eff926de269.jpg)

**Comment by gregoryagu** [comment]
Good suggestion, but I am closing this at this time.
